language: go
go:
- 1.6.3
script: make test
notifications:
  slack:
    secure: ZW954QpNClDFEh0MRYGkYi5UEIhkbe7a3rpyZAOhugaLEvx1SMo7sVyTxalobfWhtuYpUXT2pUB4usaCLtl3zJDtjshvnERcTTLwbPmwsx+J/AF/UcIkUSyvq8ooLBTUZz2SGg94u601gVxNAlQtYOcrBqwFyYMvKmFo+KI+OAYeKsxHz0cjfXLh5FLekteXwH819g5hg1Wdq+RXPwmjJP+RM8ELRefV64bkLccwsjiqDwrY5YFsY2ZAVNvSfW2yfXNDVgOE/reXrDD8WUKdfM8ro/SMNO3JYHQaMt9+EniGrk9eqL1pv+6/V11FtKIVc2J4n/tTFQPD6o6Z59GH6EWoN4vCL9zS3ICveiexWaR0U1Ummebi5NTpPhTqvURMyQVj7C/kt63lqI1GsMbWx2L9jtHO8rqfca01/B//Dgw8X7GD3nqp2t9JQrZZAIsSu/+iK18HcLWqjEYnKe3g+AWGQ2WY8Pl18dpIhqlDMFyB0EZAev5LkmCtP4nfUTZF+lwXbBYM6+gU9O5CpJzfoy73vQtJZDwb3FiSLrgdRg/S+EJSW4uOHbKTps5c8lCIMxcZfCh+sIsYfTfa+3bQDPrkUHGfDk4eiej1x1wXHUXiLkqaloz9oNDyzQUbdmvDiiHgT9XC1uWnBVvvu1ZMhJaktks3OmcsxNksiWFMtCY=
